### ISSUE TITLE
[Bug] The survey images and contents are difficult to see in the Survey List screen

### ISSUE THREAD

**Issue by minhnimble** [dquangit/survey#12]
## Issues

There are few UI issues for the survey content in  the Survey List screen. I would like to list them out as follow:
- In dark background images, we would not be able to see the status bar clearly as the texts are in black in Light mode.
- The display image for each survey item is very blurry.
- The spacing between the survey item's title and the page indicator are too far when the title content is short (within 1 line).

Example screenshot:
   <img src="https://user-images.githubusercontent.com/70877098/179457833-567336ae-df79-4809-93bd-d7f8701e42db.jpeg" width="300">

## Expect

The survey content must be clear and identical to the design regardless of the Light or Dark mode:
<img src="https://user-images.githubusercontent.com/70877098/159682538-5934d10f-fd97-4c01-b95a-28b0c6199ed8.png" width="300">

## Step to reproduce

1. Start the application freshly.
2. Login with valid credential.
3. Swipe to view different surveys in the Home screen.
4. Observe the result.

**Comment by dquangit** [comment]
Fixed in [#22](https://github.com/dquangit/survey/pull/22)

**Comment by minhnimble** [comment]
For some survey items, the status bar color is still shown in dark color for dark background contents:

 <img src="https://user-images.githubusercontent.com/70877098/179659924-72368fe0-6411-4b7a-916f-aa99e426515e.PNG" width="300">

**Comment by dquangit** [comment]
Updated in #34
